app_url: APPLICATION_URL_HERE
app_name: APPLICATION_NAME_HERE
app_logo: logo.png
base_coin: BNB
app_coin: WBNB
auto_approval: true
secret_key_base: SECRET_KEY_BASE_HERE
coingecko_url: https://api.coingecko.com/api/v3/simple/price
contract_address:
  erc721: 'ERC721_CONTRACT_ADDRESS_HERE'
rinkeby: # short_name from Network model
  gasstation_url: https://ethgasstation.info/api/ethgasAPI.json
  base_coin: ETH
  app_coin: WETH
  signer_private_key: SIGNER_PRIVATE_KEY_HERE
  ethereum_provider: https://rinkeby.infura.io/v3/ETHERESCAN_API_KEY_HERE
  explorer: "https://rinkeby.etherscan.io/"
  chainId: 4
  stdToken: ERC
matic-test: # short_name from Network model
  gasstation_url: https://gasstation-mainnet.matic.network/
  base_coin: MATIC
  app_coin: WMATIC
  signer_private_key: SIGNER_PRIVATE_KEY_HERE
  ethereum_provider: https://rpc-mumbai.maticvigil.com/
  explorer: "https://https://mumbai.polygonscan.com/"
  chainId: 8001
  stdToken: ERC
bsc-test: # short_name from Network model
  gasstation_url: https://bscgas.info/gas
  base_coin: BNB
  app_coin: WBNB
  signer_private_key: SIGNER_PRIVATE_KEY_HERE
  ethereum_provider: https://data-seed-prebsc-1-s1.binance.org:8545/
  explorer: "https://testnet.bscscan.com/" 
  chainId: 97
  stdToken: BEP
etherscan:
  api_key: API_KEY_HERE
  api_url: https://api-rinkeby.etherscan.io/api
pinata:
  api_key: PINATA_API_KEY_HERE
  api_secret: PINATA_API_SECRET_KEY_HERE
  base_url: https://api.pinata.cloud/pinning/pinFileToIPFS
default_fees:
  service_fee: 2.5
discussion_url: "DISCUSSION_URL_HERE"
support_url: SUPPORT_URL_HERE
explorer: https://testnet.bscscan.com/
opensea_url: https://rinkeby-api.opensea.io
moon_pay:
  host: https://buy-sandbox.moonpay.com
  public_key: PUBLIC_KEY_HERE
  secret_key: SECRET_KEY_HERE
  redirect_url: REDIRECT_URL_HERE
  currency_code: RINKETH