rinkeby:
  transferProxyContractAddress: 'TRANSFER_PROXY_CONTRACT_ADDRESS_HERE'
  tokenAddress: 'WETH_TOKEN_ADDRESS_HERE'
  tradeContractAddress: 'TRADE_CONTRACT_ADDRESS_HERE'
  tokenURIPrefix: 'https://gateway.pinata.cloud/ipfs/'
  tokenSymbol: WETH
bsc-test:
  transferProxyContractAddress: 'TRANSFER_PROXY_CONTRACT_ADDRESS_HERE'
  tokenAddress: 'WBNB_TOKEN_ADDRESS_HERE'
  tradeContractAddress: 'TRADE_CONTRACT_ADDRESS_HERE'
  tokenURIPrefix: 'https://gateway.pinata.cloud/ipfs/'
  tokenSymbol: WBNB
matic-test:
  transferProxyContractAddress: 'TRANSFER_PROXY_CONTRACT_ADDRESS_HERE'
  tokenAddress: 'WMATIC_TOKEN_ADDRESS_HERE'
  tradeContractAddress: 'TRADE_CONTRACT_ADDRESS_HERE'
  tokenURIPrefix: 'https://gateway.pinata.cloud/ipfs/'
  tokenSymbol: WMATIC